### ISSUE TITLE
New Super Mario Bros. U + Luigi U

### ISSUE THREAD

**Issue by mhayeck** [slashiee/cemu_graphic_packs#298]
Hi. I think your work is amazing and i'm very grateful for it. I'm having a problem when using any graphic pack for this game at higher resolutions, the error is that the background becomes all black. When I disable the graphic pack everything runs fine. It dosn't happen everywhere in the game, but in a lot of places. Like the world 2-1 or the openning cut scene if you pay attention. Is there a possibly solution? I've never had this with any game, everything runs fine and I have a intel i7 with a nvidia gpu, everything updated. Again, your work is amazing. Thanks!

![p_20181213_201033](https://user-images.githubusercontent.com/45861059/49971132-8b855500-ff14-11e8-9e8a-183d2c852154.jpg)
![p_20181213_201131](https://user-images.githubusercontent.com/45861059/49971139-95a75380-ff14-11e8-8e5e-cf782574fbf4.jpg)

**Comment by slashiee** [comment]
are your graphic packs updated? i believe this issue was fixed long ago...

**Comment by mhayeck** [comment]
Yes, they are updated. Just for sake, i've just downloaded the newest one from your site and from the master file here and the problem persists. 

![2](https://user-images.githubusercontent.com/45861059/49977512-c21b9980-ff2d-11e8-8fa5-fcbf7b449fcc.jpg)

**Comment by skalfate** [comment]
Would you be able to upload your cemu log file please. I believe I dealt and smelt that issue before.

**Comment by mhayeck** [comment]
I've downloaded another release and the error persists. I've tried another version of the Cemu too and is the same thing. Here i will post two screenshots, one with the graphic pack enabled and another with it disabled:

![1111](https://user-images.githubusercontent.com/45861059/49978424-ad410500-ff31-11e8-9f84-4f7346cd9233.jpg)

![222222](https://user-images.githubusercontent.com/45861059/49978427-b16d2280-ff31-11e8-8a93-9759e8ddd003.jpg)

So, like you said, I'm going to upload my log here. I've loaded the game again with the graphic pack enabled to make the log.

[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2678341/log.txt)

**Comment by skalfate** [comment]
Thanks for that log, the new update is published, hopefully it fixes it up for you.

**Comment by mhayeck** [comment]
Hi. I'm sorry but it didn't fix it. I will upload again the log.
Thanks for your help.

[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2678741/log.txt)

**Comment by slashiee** [comment]
are you sure you updated the pack to the latest version? it's the same error as before which doesn't seem right (consts were removed)...

**Comment by skalfate** [comment]
I am taking a look into it now.

**Comment by mhayeck** [comment]
I've tested it and everything is fine! So many thanks to you and the other people who made all of this graphics packs.

**Comment by skalfate** [comment]
Your welcome. I'll go ahead and close this issue.
